### ISSUE TITLE
Can you please compile and put result in "releases" ?

### ISSUE THREAD

**Issue by G9-Dev** [Evasionn/platformergame-rlutil#1]

**Comment by Evasionn** [comment]
Hi! you can clone and compile the project if you need executable output. If there is a problem about compilation process, you can provide an output here so I can help you. 

Good luck!

**Comment by G9-Dev** [comment]
Actually i added all files in a code::blocks project :

![image](https://user-images.githubusercontent.com/67204439/108984960-c6f14180-7690-11eb-8f76-6f0500c4efae.png)

and ... what happens... : 

![image](https://user-images.githubusercontent.com/67204439/108985091-eee0a500-7690-11eb-818d-03136c96029c.png)
